version: "3"

services:
  hugo:
    image: jojomi/hugo:latest
    volumes:
      - ./src/:/src
      - ./output/:/output
    environment:
      - HUGO_REFRESH_TIME=3600
      - HUGO_THEME=kross-hugo-portfolio-template
      - HUGO_BASEURL=https://tos.pbfp.xyz
    restart: unless-stopped

  web:
    image: jojomi/nginx-static
    volumes:
      - ./output:/var/www
    environment:
      - VIRTUAL_HOST=tos.pbfp.xyz
    ports:
      - 80:80
    restart: unless-stopped
