baseURL = "https://tos.odex.be"
languageCode = "en-us"
title = "Tom OS - GNU/Linux"
theme = "kross-hugo-portfolio-template"
summaryLength = "10"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/shuffle/shuffle.min.js"


# navigation
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about/index.html"
  weight = 2
  
  [[menu.main]]
  name = "Wiki"
  URL = "https://wiki.odex.be"
  weight = 3

  [[menu.main]]
  name = "Download"
  URL = "download/index.html"
  weight = 4

  [[menu.main]]
  name = "API"
  URL = "api/index.html"
  weight = 5
  
  [[menu.main]]
  name = "Contact"
  URL = "contact/index.html"
  weight = 6


[params]
logo = "images/logo.svg"
home = "Home"
# Meta data
description = "Homepage of TOS GNU/Linux"
author = "Tom Meyers"
# Google Analitycs
googleAnalitycsID = "Your ID"

  # Preloader
  [params.preloader]
  enable = true

  [params.contact]
  enable = true
  formAction = "https://formspree.io/tommeyers.tm127@gmail.com" #contact form works with formspree.io

  [params.footer]
  email = "tom@odex.be"
